### ISSUE TITLE
instead of `import datetime`, use `from datetime import datetime, timedelta`

### ISSUE THREAD

**Issue by ndbroadbent** [fabriceb/gcalcron#9]
Would you be in favor of replacing [`import datetime`](https://github.com/fabriceb/GCalCron2/blob/master/gcalcron2.py#L14) with `from datetime import datetime, timedelta`? 

We could then use just `datetime` and `timedelta` instead of `datetime.datetime` and `datetime.timedelta`. 

Thanks for merging my requests, by the way!

**Comment by fabriceb** [comment]
This is a personal convention I have adopted when writing Python :-)

Since there can be confusion between datetime and datetime.datetime I prefer to be explicit about it by importing only datetime and always use the same convention.

I must admit I do not know if it is the standard Python convention.

**Comment by ndbroadbent** [comment]
OK, sure, that's fair enough :)
